# sourced from https://repo1.dso.mil/platform-one/quick-start/big-bang/-/blob/master/start.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: bigbang

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: bigbang
spec:
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
    /**/*.sh
  interval: 10m
  url: https://repo1.dso.mil/big-bang/bigbang.git
  ref:
    tag: 1.55.0

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: environment
  namespace: bigbang
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: environment-repo
  path: ./base
  prune: true
